name: "test"

on:
  pull_request:
  push:
    branches: [main]

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout repository"
      uses: "actions/checkout@v2"

    - name: "Install uv"
      uses: "astral-sh/setup-uv@v6"
      with:
        version: "0.7.21"
        enable-cache: true
    - name: "Set up Python"
      uses: "actions/setup-python@v5"

    - name: "Install the project via uv"
      run: "uv sync --locked --group test"

    - name: "Run tests"
      run: "uv run pytest"
