name: website

on:
  push:
    branches: [main]
  pull_request:
  release:
    types: [published]


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install Poetry
      run: pip install poetry

    - name: Install dependencies with Poetry
      run: poetry install --with docs

    # Building
    - name: Build HTML using Poetry
      run: |
        cd docs
        poetry run make html

    # Upload
    - name: Upload artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        name: github-pages
        retention-days: 7
        path: docs/build/html/

  deploy:
    # Deploy to the github-pages environment
    # but not on PRs
    if: ${{ github.event_name != 'pull_request' }}
    needs: build
    permissions:
        id-token: write
        pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      with:
        artifact_name: github-pages
        preview: true

  post-page-artifact:
    if: ${{ github.event_name == 'pull_request' }}
    needs: build
    runs-on: ubuntu-latest
    permissions:
        pull-requests: write
        actions: read
    steps:
      - name: Post comment preview
        uses: CDCgov/cfa-actions/post-artifact@v1.0.0
        with:
          artifact-name: github-pages
          gh-token: ${{ secrets.GITHUB_TOKEN}}
