name: "azuretools website"

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: "Checkout repository"
      uses: "actions/checkout@v2"

    - name: "Install uv"
      uses: "astral-sh/setup-uv@v6"
      with:
        version: "0.7.21"
        enable-cache: true

    - name: "Set up Python"
      uses: "actions/setup-python@v5"

    - name: "Install the project via uv"
      run: "uv sync --locked --group docs"

    - name: "Build HTML using uv"
      run: |
        cd docs
        uv run make html

    # Upload
    - name: Upload artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        name: github-pages
        retention-days: 7
        path: docs/build/html/

  deploy:
    # Deploy to the github-pages environment on pushes to main only
    if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    needs: "build"
    permissions:
        id-token: "write"
        pages: "write"
    environment:
      name: "github-pages"
      url: "${{ steps.deployment.outputs.page_url }}"

    # Specify runner + deployment step
    runs-on: ubuntu-latest

    steps:
    - name: "Deploy to GitHub Pages"
      uses: "actions/deploy-pages@v4"
      with:
        artifact_name: "github-pages"
        preview: true

  post-page-artifact:
    if: "${{ github.event_name == 'pull_request' }}"
    needs: "build"
    runs-on: "ubuntu-latest"
    permissions:
        pull-requests: "write"
        actions: "read"
    steps:
      - name: "Post comment preview"
        uses: "CDCgov/cfa-actions/post-artifact@v1.0.0"
        with:
          artifact-name: "github-pages"
          gh-token: "${{ secrets.GITHUB_TOKEN}}"
